[package]
name = "rust_test"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.5"
libc = "0.2"
axum = { version = "0.7", features = ["tokio", "http1"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
